sudo: false
language: python
python:
  - "3.5"
env:
  - JEKYLL_ENV=production
before_install:
  - rvm use 2.3.3 --install --fuzzy
  - tar -xvf jsbsim-code.tar.gz

install:
 - cd jsbsim-code
 - ./autogen.sh
 - make
 - export PATH=$PATH:$PWD/src/
 - cd ..
 - gem install --no-document jekyll
 - gem install jekyll-scholar
 - pip install --use-wheel jupyter
 - pip install --use-wheel numpy
 - pip install --use-wheel matplotlib

script:
 - python -m matplotlib.pyplot
 - make deploy
