title: Lambda-4S
subtitle: The Smallest Orbital Rocket
nav:
  - title: Lambda-4S Overview
    url: /Lambda-4S/
    name: home
  - title: History
    url: /Lambda-4S/history/
    name: history
  - title: Digitized Data
    url: /Lambda-4S/data/
    name: data
  - title: Simulation
    url: /Lambda-4S/simulation/
    name: simulation

subnav:
    home:
      - title: Overview
        url: /Lambda-4S/
        name: overview
      - title: First Stage
        url: /Lambda-4S/overview/stage1/
        name: stage1
      - title: Second Stage
        url: /Lambda-4S/overview/stage2/
        name: stage2
      - title: Third Stage
        url: /Lambda-4S/overview/stage3/
        name: stage3
      - title: Guidance and Electronics
        url: /Lambda-4S/overview/gnc/
        name: gnc
      - title: Fourth Stage and Payload
        url: /Lambda-4S/overview/payload/
        name: payload

    data:
      - title: Overview
        url: /Lambda-4S/data/
        name: data
      - title: First Stage Thrust Curve
        url: /Lambda-4S/data/stage1/
        name: stage1

